### ISSUE TITLE
package down and vignettes

### ISSUE THREAD

**Issue by jebyrnes** [nasa/NASAaccess#1]
This is an awesome package! Any chance there might be some vignettes and a pkgdown site (https://github.com/r-lib/pkgdown ) to go with it to increase accessibility to the broader user community?

**Comment by imohamme** [comment]
Thanks for your comment. Accessibility to the broader community is certainly our goal for this work. Will look at your suggestions in the near future.

**Comment by imohamme** [comment]
Vignettes are created and website has been build https://imohamme.github.io/NASAaccess/

Thanks!
