### ISSUE TITLE
Advise to install the package. Help...

### ISSUE THREAD

**Issue by petermingjing** [nasa/NASAaccess#5]
> install_github("nasa/NASAaccess", build_vignettes = TRUE)
Downloading GitHub repo nasa/NASAaccess@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/7w/0t3xsr8d06s9yndqn7gxl_h80000gn/T/Rtmp0aOggl/remotes1380116490986/nasa-NASAaccess-e2707e1/DESCRIPTION’ ...
─  preparing ‘NASAaccess’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (11.4s)
   --- re-building ‘About.Rmd’ using rmarkdown
   --- finished re-building ‘About.Rmd’
   
   --- re-building ‘GLDAS.Rmd’ using rmarkdown
   --- finished re-building ‘GLDAS.Rmd’
   
   --- re-building ‘GPM.Rmd’ using rmarkdown
   
   Quitting from lines 30-71 [unnamed-chunk-2] (GPM.Rmd)
   Error: processing vignette 'GPM.Rmd' failed with diagnostics:
   there is no package called 'ggmap'
   --- failed re-building ‘GPM.Rmd’
   
   --- re-building ‘NEXGDDP-CMIP6.Rmd’ using rmarkdown
   --- finished re-building ‘NEXGDDP-CMIP6.Rmd’
   
   --- re-building ‘NEXGDDP.Rmd’ using rmarkdown
   --- finished re-building ‘NEXGDDP.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘GPM.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'NASAaccess' from GitHub:
  ! System command 'R' failed

**Comment by seyounger** [comment]
I solved this by first installing the `ggmap` package based on the line below from the error message.

"Error: processing vignette 'GPM.Rmd' failed with diagnostics: there is no package called 'ggmap'"

**Comment by petermingjing** [comment]
You are right. After installing the ggmap, NASAaccess is successfully installed. Thank you.
