### ISSUE TITLE
Required packages removed from CRAN

### ISSUE THREAD

**Issue by logopoiesis** [nasa/NASAaccess#7]
Dear Sir,
I have been trying to install NASAaccess in RStudio, using a M1 MacBook notebook. I recently updated my R Version. Unfortunately, when I attempted the installation as indicated in the instructions, the system indicates that libraries rgdal, rgeos and maptools have been retired from CRAN, as part of a long term strategy to migrate access to GDAL libraries through sf and Terra packages. I will attempt to use NASAaccess through Anaconda, but I would like to know if there are any plans to address these changes in the R version?. Thank you for any comments,
best regards,

Fabio Labra

**Comment by imohamme** [comment]
Hi @logopoiesis ,
Thanks for trying out NASAaccess!
NASAaccess version 4.0.0 has addressed all these retired libraries. Dependency on rgdal, rgeos, and maptools has been removed and replaced with terra.

**Comment by imohamme** [comment]
NASAaccess V4.0.0 has been released!
